In [1]:
%cd "d:\KIM\020_Project\260207.010_금융데이터\src"

from kis import kis_api
import pandas as pd

[Errno 2] No such file or directory: 'd:\\KIM\\020_Project\\260207.010_금융데이터\\src'
/app/notebook

In [2]:
kis_api.domestic_stock_inquire_psbl_rvsecncl()

{'ctx_area_fk100': '74204489^01^                                                                                        ',
 'ctx_area_nk100': '                                                                                                    ',
 'output': [],
 'rt_cd': '0',
 'msg_cd': 'KIOK0560',
 'msg1': '조회할 내용이 없습니다                                                          '}

In [3]:
r = kis_api.domestic_stock_inquire_daily_ccld("", "")
df = pd.DataFrame(r.get('output1'))
cols = ['ord_dt', 'ord_tmd', 'ord_gno_brno', 'odno', 'orgn_odno', 'pdno', 'prdt_name', 'ord_dvsn_name', 'sll_buy_dvsn_cd', 'sll_buy_dvsn_cd_name', 'ord_qty', 'tot_ccld_qty', 'cncl_yn', 'ord_dvsn_cd', 'rmn_qty', 'rjct_qty']
df[cols]

20260225
20260226

,ord_dt,ord_tmd,ord_gno_brno,odno,orgn_odno,pdno,prdt_name,ord_dvsn_name,sll_buy_dvsn_cd,sll_buy_dvsn_cd_name,ord_qty,tot_ccld_qty,cncl_yn,ord_dvsn_cd,rmn_qty,rjct_qty
0,20260226,090712,91259,0007455100,0005687300,012205,계양전기우,시장가,02,매수취소*,1,0,,01,0,0
1,20260226,090304,91259,0006293200,,012200,계양전기,시장가,01,현금매도,1,1,,01,0,0
2,20260226,090301,91259,0006277400,,009310,참엔지니어링,시장가,01,현금매도,1,1,,01,0,0
3,20260226,090105,91259,0005693500,,012200,계양전기,시장가,02,현금매수,1,1,,01,0,0
4,20260226,090103,91259,0005687300,,012205,계양전기우,시장가,02,현금매수,1,0,,01,0,0
5,20260226,090102,91259,0005677900,,009310,참엔지니어링,시장가,02,현금매수,1,1,,01,0,0
6,20260225,090305,91259,0005825500,,489790,한화비전,시장가,01,현금매도,1,1,,01,0,0
7,20260225,090304,91259,0005821000,,006200,한국전자홀딩스,시장가,01,현금매도,1,1,,01,0,0
8,20260225,090303,91259,0005814500,,092220,KEC,시장가,01,현금매도,1,1,,01,0,0
9,20260225,090301,91259,0005808200,,007460,에이프로젠,시장가,01,현금매도,1,1,,01,0,0
10,20260225,090110,91259,0005294300,,489790,한화비전,시장가,02,현금매수,1,1,,01,0,0
11,20260225,090108,91259,0005287900,,006200,한국전자홀딩스,시장가,02,현금매수,1,1,,01,0,0
12,20260225,090107,91259,0005279800,,092220,KEC,시장가,02,현금매수,1,1,,01,0,0
13,20260225,090101,91259,0005255000,,007460,에이프로젠,시장가,02,현금매수,1,1,,01,0,0

In [31]:
pd.DataFrame(kis_api.domestic_stock_inquire_balance()["output1"])

,pdno,prdt_name,trad_dvsn_name,bfdy_buy_qty,bfdy_sll_qty,thdt_buyqty,thdt_sll_qty,hldg_qty,ord_psbl_qty,pchs_avg_pric,...,loan_dt,loan_amt,stln_slng_chgs,expd_dt,fltt_rt,bfdy_cprs_icdc,item_mgna_rt_name,grta_rt_name,sbst_pric,stck_loan_unpr
0,006200,한국전자홀딩스,현금,1,1,0,0,0,0,0.0000,...,,0,0,,-4.29378531,-38,100%,불가,630,0.0000
1,007460,에이프로젠,현금,1,1,0,0,0,0,0.0000,...,,0,0,,-4.11255411,-19,100%,불가,330,0.0000
2,009310,참엔지니어링,현금,0,0,1,1,0,0,0.0000,...,,0,0,,15.71546733,190,100%,불가,770,0.0000
3,012200,계양전기,현금,0,0,1,1,0,0,0.0000,...,,0,0,,-11.55943293,-1060,100%,불가,6230,0.0000
4,092220,KEC,현금,1,1,0,0,0,0,0.0000,...,,0,0,,4.53781513,54,100%,불가,850,0.0000
5,489790,한화비전,현금,1,1,0,0,0,0,0.0000,...,,0,0,,5.93667546,4500,100%,불가,54570,0.0000

In [5]:
kis_api.query_av_buy("001515")

{'output': {'ord_psbl_cash': '164323',
  'ord_psbl_sbst': '0',
  'ruse_psbl_amt': '45798',
  'fund_rpch_chgs': '0',
  'psbl_qty_calc_unpr': '3815',
  'nrcvb_buy_amt': '207699',
  'nrcvb_buy_qty': '54',
  'max_buy_amt': '207699',
  'max_buy_qty': '54',
  'cma_evlu_amt': '0',
  'ovrs_re_use_amt_wcrc': '0',
  'ord_psbl_frcr_amt_wcrc': '0'},
 'rt_cd': '0',
 'msg_cd': 'KIOK0510',
 'msg1': '조회가 완료되었습니다                                                           '}

In [6]:
kis_api.query_av_sell(code="323410")

{'output': {'pdno': '323410',
  'prdt_name': '',
  'buy_qty': '0',
  'sll_qty': '0',
  'cblc_qty': '0',
  'nsvg_qty': '0',
  'ord_psbl_qty': '0',
  'pchs_avg_pric': '0.0000',
  'pchs_amt': '0',
  'now_pric': '0',
  'evlu_amt': '0',
  'evlu_pfls_amt': '0',
  'evlu_pfls_rt': '0.00'},
 'rt_cd': '0',
 'msg_cd': 'KIOK0420',
 'msg1': '정상적으로 조회되었습니다                                                       '}

In [4]:
kis_api.domestic_stock_inquire_daily_ccld()

{'ctx_area_fk100': '74204489^01^20250201^20250223^ ^00^00^ALL^                                                          ',
 'ctx_area_nk100': '                                                                                                    ',
 'output1': [],
 'output2': {'tot_ord_qty': '0',
  'tot_ccld_qty': '0',
  'tot_ccld_amt': '0',
  'prsm_tlex_smtl': '0',
  'pchs_avg_pric': '0.0000'},
 'rt_cd': '0',
 'msg_cd': 'KIOK0560',
 'msg1': '조회할 내용이 없습니다                                                          '}