In [1]:
from alpha.data import local

In [4]:
ds = local.AlphaDataStore()

In [5]:
ds.ohlcv(symbol="000660", seconds=60)

                          open       high        low      close    volume
dt
2026-08-24 09:01:00    68012.0    68212.0    68012.0    68112.0    1441.0
2026-08-24 09:01:00    67912.0    68612.0    67912.0    68512.0    4365.0
2026-08-24 09:01:00    68512.0    69312.0    68512.0    69312.0    2220.0
2026-08-24 09:01:00  1775000.0  1780000.0  1768000.0  1775000.0  107965.0
2026-08-24 09:02:00    69312.0    69512.0    68812.0    69312.0    9017.0
...                        ...        ...        ...        ...       ...
2026-08-28 12:09:00  1695000.0  1695000.0  1693000.0  1693000.0    6443.0
2026-08-28 12:10:00  1694000.0  1695000.0  1693000.0  1693000.0    5741.0
2026-08-28 12:24:00  1692000.0  1693000.0  1691000.0  1693000.0    1946.0
2026-08-28 12:25:00  1692000.0  1693000.0  1692000.0  1692000.0    1202.0
2026-08-28 12:29:00  1692000.0  1692000.0  1691000.0  1691000.0     181.0

[711 rows x 5 columns]

In [2]:
dss = local.AlphaDataStore(live=False)

In [3]:
dss.ohlcv(symbol="000660", seconds=60)

                        open     high      low    close  volume
dt
2026-08-25 09:01:00  68012.0  68212.0  68012.0  68112.0  1441.0
2026-08-25 09:01:00  67912.0  68612.0  67912.0  68512.0  4365.0
2026-08-25 09:01:00  68512.0  69312.0  68512.0  69312.0  2220.0
2026-08-25 09:02:00  69312.0  69512.0  68812.0  68812.0  8067.0
2026-08-25 09:02:00  69012.0  69312.0  69012.0  69312.0   950.0
...                      ...      ...      ...      ...     ...
2026-08-30 09:10:00  63612.0  63912.0  63512.0  63712.0  1415.0
2026-08-30 09:10:00  63912.0  63912.0  63512.0  63612.0  1970.0
2026-08-30 09:10:00  63412.0  63412.0  63012.0  63212.0   821.0
2026-08-30 09:10:00  63212.0  63212.0  62412.0  62512.0  2736.0
2026-08-30 09:10:00  61712.0  61712.0  61612.0  61612.0  1100.0

[2150 rows x 5 columns]