In [1]:
from pykrx import stock
import time
import pandas as pd

# 1) 날짜 범위 (예: 오늘 기준 2년)
end = pd.Timestamp.today().strftime("%Y%m%d")
start = (pd.Timestamp.today() - pd.DateOffset(years=2)).strftime("%Y%m%d")

days = stock.get_previous_business_days(fromdate=start, todate=end)
kospi = stock.get_market_ohlcv_by_ticker(days[0], market="KOSPI")
kospi

,시가,고가,저가,종가,거래량,거래대금,등락률,시가총액
티커,,,,,,,,
095570,4845,4900,4805,4895,138511,669906000,0.820000,221512255305
006840,17610,17750,17000,17390,18472,319923540,-1.190000,230375085790
027410,4080,4200,4060,4155,359399,1489311920,1.960000,397703266605
282330,134400,135100,133000,133000,41395,5540071500,-0.080000,2298759498000
138930,7880,7980,7770,7810,1659665,13060071440,-0.130000,2515510700780
...,...,...,...,...,...,...,...,...
079980,4000,4025,3975,4005,55958,223733385,0.130000,138172500000
005010,5750,5990,5600,5870,1692131,9789226490,4.260000,329824000250
000540,5280,5280,5280,5280,938906,4957423680,29.889999,339201165600
000545,7350,7570,7350,7570,132789,1000146790,29.850000,5813760000
003280,3085,3110,3030,3060,1404642,4311948235,0.160000,735700190940

In [5]:
kospi.nlargest(10, "시가총액").index.to_list()

['005930',
 '000660',
 '373220',
 '207940',
 '005380',
 '005935',
 '000270',
 '068270',
 '005490',
 '035420']

In [ ]:
date = "20240201"  # YYYYMMDD

df_kospi = stock.get_market_fundamental_by_ticker(date, market="KOSPI")
df_kospi

          BPS    PER   PBR    EPS   DIV   DPS
티커
095570   8076  23.73  0.59    201  5.66   270
006840  41948   0.00  0.41      0  1.16   200
027410  16528  16.36  0.24    247  2.72   110
282330  55724  12.57  2.53  11203  2.91  4100
138930  30468   3.27  0.26   2404  7.94   625
...       ...    ...   ...    ...   ...   ...
079980  11585   0.00  0.34      0  0.00     0
005010  16181   0.94  0.33   5675  6.55   350
000540  11050   2.04  0.40   2142  0.00     0
000545      0   0.00  0.00      0  0.00     0
003280    544  32.77  5.66     94  0.00     0

[924 rows x 6 columns]

In [7]:
cap_kospi = stock.get_market_cap_by_ticker(date, market="KOSPI")
cap_kospi

            종가             시가총액       거래량           거래대금       상장주식수
티커
005930   73600  439375995680000  19881033  1460989435744  5969782550
000660  132700   96605913835500   3778274   503287491300   728002365
373220  381500   89271000000000    232165    87826540500   234000000
207940  829000   59003246000000     86022    71062300000    71174000
005935   59700   49126335990000   1291675    76755173287   822886700
...        ...              ...       ...            ...         ...
014915    6210       3726000000      1791       10945060      600000
002787   12580       3708684640         4          50710      294808
001527   11720       3616428680       657        7686940      308569
002785    4200       3600315600      1468        6239070      857218
001525    5760       3558130560       220        1249240      617731

[953 rows x 5 columns]